# Generated by Django 6.0.6 on 2026-06-20 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shuju',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lianxiren', models.CharField(max_length=100, verbose_name='联系人')),
                ('lianxidianhua', models.CharField(max_length=20, verbose_name='联系电话')),
                ('dianziyoujian', models.EmailField(max_length=254, verbose_name='电子邮件')),
                ('yaoqiushuoming', models.TextField(verbose_name='要求说明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '联系表单数据',
                'verbose_name_plural': '联系表单数据',
                'db_table': 'shuju',
            },
        ),
    ]
